name: test parser workflow
on:
  push:
    branches:
      - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make cmake
    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --timeout 10 --verbose -R "SQL_compiler_test_parser"
