name: test parser workflow
on:
  push:
    branches:
      - '*'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'recursive'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make cmake
        git submodule update --init
    - name: Configure and build
      run: |
        bash init.sh
        mkdir build
        cd build
        cmake -DMAIN=OFF -DTEST_PARSER=ON ..
        make
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --timeout 10 --verbose -R "SQL_compiler_test_parser"
